version = 0.1
extensions = [
  'chomp@0.1:swc',
  './packages/chomp-extensions/dts.js',
  './packages/chomp-extensions/pkg.js'
]

[env]
PACKAGE_MANAGER = 'pnpm'

[[task]]
name = "clean"
run = "rm -rf packages/@*/*/dist"

[[task]]
name = "build"
deps = ["mdit", "tagged-templates", "utils"]

[[task]]
name = "mdit"
template = "pkg"
template-options = { root = "packages/@jsergo/mdit" }

[[task]]
name = "tagged-templates"
template = "pkg"
template-options = { root = "packages/@jsergo/tagged-templates" }
display = "init-only"

[[task]]
name = "utils"
template = "pkg"
template-options = { root = "packages/@wycatsjs/utils" }
display = "init-only"
