version = 0.1
extensions = [
  'chomp@0.1:swc',
  './packages/chomp-extensions/dts.js',
  './packages/chomp-extensions/pkg.js',
  './packages/chomp-extensions/postcss.js',
  './packages/chomp-extensions/inline-css.js',
]

[env]
PACKAGE_MANAGER = 'pnpm'

[[task]]
name = "clean"
deps = ["clean:src", "clean:dist"]

[[task]]
name = "clean:dist"
run = "rm -rf packages/@*/*/dist"


[[task]]
name = "clean:src"
engine = "node"
run = """
import glob from 'fast-glob';
import { rmSync } from 'node:fs';
const files = glob.sync('packages/@*/*/src/**/*.css.ts');

for (const file of files) {
  rmSync(file);
}
"""

[[task]]
name = "build"
serial = true
deps = [
  "vue-jsx-runtime",
  "mdit",
  "tagged-templates",
  "utils",
  "fenced-container",
  "snippets",
  "custom-block",
  "theme",
]

[[task]]
name = "build:pre"
deps = ["snippets:postcss", "custom-block:postcss", "theme:postcss"]

[[task]]
name = "mdit"
template = "pkg"
template-options = { root = "packages/@jsergo/mdit" }

[[task]]
name = "tagged-templates"
template = "pkg"
template-options = { root = "packages/@jsergo/tagged-templates" }

[[task]]
name = "utils"
template = "pkg"
template-options = { root = "packages/@wycatsjs/utils" }

[[task]]
name = "fenced-container"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/fenced-container" }

[[task]]
name = "custom-block"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/custom-block" }

[[task]]
name = "custom-block:postcss"
template = "postcss"
template-options = { root = "packages/@starbeam-docs/custom-block" }

[[task]]
name = "vue-jsx-runtime"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/vue-jsx-runtime" }

[[task]]
name = "snippets"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/snippets" }

[[task]]
name = "snippets:postcss"
template = "postcss"
template-options = { root = "packages/@starbeam-docs/snippets" }


[[task]]
name = "theme"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/theme" }

[[task]]
name = "theme:postcss"
template = "postcss"
template-options = { root = "packages/@starbeam-docs/theme" }
