version = 0.1
extensions = [
  'chomp@0.1:swc',
  './packages/chomp-extensions/dts.js',
  './packages/chomp-extensions/pkg.js',
  './packages/chomp-extensions/postcss.js',
]

[env]
PACKAGE_MANAGER = 'pnpm'

[[task]]
name = "clean"
run = "rm -rf packages/@*/*/dist; rm -f packages/@*/src/*.css.ts"

[[task]]
name = "build"
serial = true
deps = ["mdit", "tagged-templates", "utils", "fenced-container", "snippets:postcss", "snippets"]

[[task]]
name = "mdit"
template = "pkg"
template-options = { root = "packages/@jsergo/mdit" }

[[task]]
name = "tagged-templates"
template = "pkg"
template-options = { root = "packages/@jsergo/tagged-templates" }

[[task]]
name = "utils"
template = "pkg"
template-options = { root = "packages/@wycatsjs/utils" }

[[task]]
name = "fenced-container"
template = "pkg"
template-options = { root = "packages/@starbeam-docs/fenced-container" }

[[task]]
name = "snippets"
deps = ["snippets:postcss"]
template = "pkg"
template-options = { root = "packages/@starbeam-docs/snippets" }

[[task]]
name = "snippets:postcss"
template = "postcss"
template-options = { root = "packages/@starbeam-docs/snippets" }
