direction: right
Sequence: "" {
  shape: sequence_diagram

  display: "display" {
    shape: rectangle

    style: {
      font-size: 25
      font-color: "#14485f"
      fill: "#92C6E1"
      stroke: "#043d53"
      double-border: true
      bold: true
    }
  }

  Person: Person {
    shape: package
    style: {
      font-size: 30
      fill: "#E3E8D2"
      stroke: "#5F6933"
      font-color: "#5c6347"
    }
  }

  displayPhone: "displayPhone()" {
    shape: rectangle
    style: {
      font-size: 25
      fill: "#ecd265"
      font-color: "#5f4f00"
      stroke: "#5f4f00"
    }
  }
  Contact: {
    shape: package
    style: {
      multiple: true
      font-size: 30
      fill: "#E3E8D2"
      stroke: "#5F6933"
      font-color: "#5c6347"
    }
  }

  read cells: "" {
    style: {
      fill: "#E3E8D2"
    }
    Person.t -> display.t: "read name" {
      style: {
        animated: true
        font-color: "#004947"
        stroke: "#2d716e"
        stroke-dash: 2
      }
    }
    Person.t -> display.t: "read location" {
      style: {
        animated: true
        font-color: "#004947"
        stroke: "#2d716e"
        stroke-dash: 2
      }
    }
    Person.t -> display.t: "read contacts" {
      style: {
        animated: true
        font-color: "#004947"
        stroke: "#2d716e"
        stroke-dash: 2
      }
    }
  }

  Contact.t -> display.t: "iterate contacts" {
    style: {
      animated: true
      font-color: "#004947"
      stroke: "#2d716e"
      stroke-dash: 2
    }
  }

  read list of contacts: "" {
    style: {
      fill: "#ecd265"
    }
    display.t -> displayPhone.t: "call displayPhone with contact" {
      style: {
        stroke: "#96a16c"
      }
    }

    read home: "" {
      Contact.t -> displayPhone.t: "read home.type" {
        style: {
          animated: true
          font-color: "#004947"
          stroke: "#2d716e"
          stroke-dash: 2
        }
      }
      Contact.t -> displayPhone.t: "read home.number" {
        style: {
          animated: true
          font-color: "#004947"
          stroke: "#2d716e"
          stroke-dash: 2
        }
      }
    }
    read work: "" {
      Contact.t -> displayPhone.t: "read work.type" {
        style: {
          animated: true
          font-color: "#004947"
          stroke: "#2d716e"
          stroke-dash: 2
        }
      }
      Contact.t -> displayPhone.t: "read work.number" {
        style: {
          animated: true
          font-color: "#004947"
          stroke: "#2d716e"
          stroke-dash: 2
        }
      }
    }

    displayPhone.t -> display.t: "return rendered contact" {
      style: {
        stroke: "#96a16c"
      }
    }
  }

  display.t.style: {
    fill: json:"n1"
    stroke: "#043d53"
  }

  displayPhone.t.style: {
    fill: "#ecd265"
    stroke: "#5f4f00"
  }

  Person.t.style: {
    fill: "#E3E8D2"
    stroke: "#5F6933"
  }

  Contact.t.style: {
    fill: "#E3E8D2"
    stroke: "#5F6933"
  }
}