// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Monaco: typeof import('./components/repl/parent/Monaco.vue')['default']
    Output: typeof import('./components/repl/parent/Output.vue')['default']
    Repl: typeof import('./components/repl/Repl.vue')['default']
  }
}

export {}
