// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399

import { RouterLink, RouterView } from "vue-router";
import Language from "./.vitepress/components/code/Language.vue";
import Demo from "./.vitepress/components/Demo/Demo.vue";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    RouterLink: typeof RouterLink;
    RouterView: typeof RouterView;
    Demo: typeof Demo;
    Language: typeof Language;
  }
}
